---
# essential tasks. should run on all nodes
 - name: creating devops group 
   group: 
     name: devops 
     state: present

 - name: create devops user with admin previleges
   user: 
     name: devops 
     comment: Devops User 
     uid: 2001 
     group: devops

 - name: ensure HTOP is at the latest version
   yum:
     name: htop
     state: latest 
